version: '2.2'
services:
  backend-business:
    image:  'registry.cn-beijing.aliyuncs.com/meowbite/gitlab:9.4.5-ce.0'
    volumes:
      - ./config:/etc/gitlab
      - ./log:/var/log/gitlab
      - ./data:/var/opt/gitlab
    restart: always
    mem_limit: 6000000000
    ports:
      - "80:80"
      - "443:443"
